### ISSUE TITLE
[USER STORY] Accept Offering

### ISSUE THREAD

**Issue by Niravanaa** [Niravanaa/Alouer-SOEN342#9]
### 🚀 Story Summary:
As an Instructor, I want to accept available offerings that match my skills and availability so that I can teach those lessons.

### 📋 Tasks:
- [ ] Display available offerings filtered by skills and availability.
- [ ] Implement a function for accepting an offering.
- [ ] Mark the offering as unavailable once accepted.

### 📝 Additional Context:
- Offerings must be filtered by the instructor’s skills and availability.
- The offering must be marked as unavailable once accepted by an instructor.
